# Generated by Django 6.0.1 on 2026-01-30 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.DecimalField(decimal_places=2, max_digits=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=15)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('client_name', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='paused', max_length=30)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.freelancer')),
            ],
        ),
    ]
